### PR TITLE
[MainComponent] Load Router instead of BrowserRouter

### PR DESCRIPTION
**Pull request by strand**
Resolves https://azsrels.visualstudio.com/Azure%20SRE%20and%20Live%20Site/_workitems/edit/45918

### CODE REVIEW

**Comment by macrobug** [comment]
Should this require a unit test? Were we using any feature from BrowseRouter at all?

**Comment by strand** [comment]
@maggiepint Is removing the BrowserRouter dependency an acceptable solution here?

**Comment by strand** [comment]
@macrobug If I had any idea what behavior changes this will cause, if any, I would have written a spec.

**Comment by macrobug** [comment]
@strand I have no idea neither. If routing seems to work fine, as in one can navigate across pages, then it should be ok.

**Comment by maggiepint** [comment]
I believe that when I added browser router back in the day, it was because that preserved the history with the back button. I think that react router has revved major versions since then, and it may be that this code is just plain deprecated. If the back button still works, then I imagine this PR is fine.

**Comment by strand** [comment]
There is a back button bug which exists on master without this change. When navigating the application, the back button requires two presses to go back one page, another three (for a total of five) to go back two pages, and another three (total of 8) clicks to go back three pages.

back-button-bug

However, since this bug exists in _either_ master or this PR, I think this bug is not related to this work.

**Pull request merged**
